#!/usr/bin/env python3
"""The findings the calibration bias produced: apparent finding, registered
challenge, pre-calibration outcome, and what the calibration correction showed.

Set A. Distinct from figures/T1-false-findings.md, which is a different set.

Every quotation is verified against the committed file at the commit named in
the row before anything is printed, so no cell is written from memory. Numbers
come from the artefacts named beside them. No table number is assigned.

Usage: python3 scripts/make_calibration_findings.py > figures/calibration-artefact-findings.md
"""
import json
import subprocess
import sys

E2E = json.load(open('results/E2E-analysis.json'))
W8 = json.load(open('results/W8-effect-size-accounting.json'))

# (commit, path, fragment). commit=None means check the working copy: the
# reports are regenerated artefacts and their wording tracks their generators,
# whereas the plans are registration-grade and are pinned to the commit that
# registered them.
QUOTES = {
    'D':        ('c823393', 'results/E2-PLAN.md',   'D   = m50 - m10 = 0.0689'),
    'conc_crit':('c823393', 'results/E2-PLAN.md',   '**CONCURRENCY-DRIVEN** | both `f ≤ 0.25`'),
    'cap_crit': ('c823393', 'results/E2-PLAN.md',   '**CAP-DRIVEN** | both `f ≥ 0.75`'),
    'f_verdict':(None,      'results/E2-REPORT.md', 'Registered verdict: **OFF-SCALE** (f = +0.000 and -0.006).'),
    'f_nomove': (None,      'results/E2-REPORT.md', 'neither cell moved materially in either direction'),
    'h_crit':   ('a741d68', 'results/E2B-PLAN.md',  '**h >= 0.75** | **S GOVERNS.**'),
    'h_value':  (None,      'results/E2B-REPORT.md','h = (rho* - rho10) / D = (0.98 - 0.9137) / 0.0689 = +0.980'),
    'a6_conc':  ('c3aee75', 'PRE-REGISTRATION.md',  '| concurrency gap | 0.0689 | 0.0688–0.0698 | **survives** |'),
    'a6_cap':   ('c3aee75', 'PRE-REGISTRATION.md',  '| E2 cap swap | identical intervals, f = 0.001 | identical rate intervals, f = 0.000 | **survives, and is stronger** — rate is estimator-independent |'),
    'a6_h':     ('c3aee75', 'PRE-REGISTRATION.md',  '| E2b, S governs | h = 0.980 | h = 0.895–0.945 | **survives** |'),
}


def verify():
    """Every fragment must be present at its commit, or nothing is printed."""
    bad = []
    for key, (commit, path, frag) in QUOTES.items():
        if commit is None:
            body = open(path, encoding='utf-8').read()
            where = path
        else:
            try:
                body = subprocess.run(['git', 'show', '%s:%s' % (commit, path)],
                                      capture_output=True, text=True,
                                      check=True).stdout
            except subprocess.CalledProcessError:
                bad.append('%s: cannot read %s at %s' % (key, path, commit))
                continue
            where = '%s at %s' % (path, commit)
        if frag not in body:
            bad.append('%s: fragment absent from %s' % (key, where))
    if bad:
        for b in bad:
            print('QUOTE CHECK FAILED — %s' % b, file=sys.stderr)
        raise SystemExit(1)


def main():
    verify()
    c10, c50 = E2E['cells']['c10'], E2E['cells']['c50']
    m, a4 = W8['matched'], W8['matchedA4']

    print('# The findings the calibration bias produced')
    print()
    print('Three attributions of one gap, each registered with its falsification '
          'criterion before the data that tested it were collected. Generated by '
          '`scripts/make_calibration_findings.py`. Every quotation is verified '
          'before the table is written: quotations from the plans and from A6 '
          'against the committed file at the commit named, quotations from the '
          'reports against the working copy, because the reports are regenerated '
          'artefacts whose wording tracks their generators. Numbers come from the '
          'artefacts named in the sources below. This is a different set from '
          '`figures/T1-false-findings.md`.')
    print()
    print('| Apparent finding | Registered falsification / challenge | '
          'Pre-calibration outcome | What the calibration correction showed |')
    print('|---|---|---|---|')

    print('| **The boundary depended on concurrency.** The two E1 arms separated '
          'by `D = m50 - m10 = 0.0689` in safe utilisation, 0.9137 at concurrency '
          '10 against 0.9826 at concurrency 50. '
          '| Swap the admission limits across the arms and score the fraction of '
          '`D` that moves with the cap: **CONCURRENCY-DRIVEN** requires both '
          '`f ≤ 0.25` (E2 plan, `c823393`). '
          '| Confirmed. `f = +0.000` and `-0.006`: neither cell moved toward the '
          'other arm, so the gap did not follow the cap (E2 report). '
          '| Dissolved. Under one recipe applied to both corpora the same '
          'inter-arm gap falls from **%.4f to %.4f** (%.0f%% removed) on the '
          'drain-window estimator, and from %.4f to %.4f (%.0f%% removed) on the '
          'delivery-span one — %.1f rps to %.1f rps in throughput terms. |'
          % (m['gapRhoUncorrected'], m['gapRhoCorrected'], m['fractionRemovedRho'],
             a4['gapRhoUncorrected'], a4['gapRhoCorrected'], a4['fractionRemovedRho'],
             m['gapRpsUncorrected'], m['gapRpsCorrected']))

    print('| **The boundary depended on the admission limit.** The E1 arms had '
          'been run at different queue caps — 500 at concurrency 10, 2500 at '
          'concurrency 50 — so the cap was a live explanation of `D`. '
          '| The same swap, scored the other way: **CAP-DRIVEN** requires both '
          '`f ≥ 0.75` (E2 plan, `c823393`). '
          '| **Refuted before calibration.** Registered verdict OFF-SCALE, '
          '`f = +0.000` and `-0.006`; `CAP-DRIVEN` was unreachable once the first '
          'cell returned +0.000, and neither cell moved materially in either '
          'direction (E2 report). '
          '| **No corrected-harness artefact addresses this row.** The corrected '
          'corpus ran only the original diagonal — c10 at cap 500, c50 at cap '
          '2500 — so the swapped-cap cells were never re-measured after the '
          'correction, and no post-calibration value of `f` exists. |')

    print('| **Service time governed the boundary.** With concurrency and service '
          'time separated at `C = 400`, ρ* landed c50-like rather than c10-like. '
          '| Score ρ* against the two E1 midpoints: `h = (ρ*_E2b − ρ10) / D`, '
          'where **`h ≥ 0.75` reads S GOVERNS** and `h ≤ 0.25` reads concurrency '
          'governs (E2b plan, `a741d68`, with a dead band registered in advance). '
          '| Confirmed. `h = (0.98 − 0.9137) / 0.0689 = +0.980` (E2b report), at '
          'the S-governs end of the scale. '
          '| **No corrected-harness artefact recomputes `h`.** No corrected cell '
          'was run at `C = 400`: the corrected corpus is two cells at `C = 2000`. '
          'The arm gap that `h` is scored against does collapse (row 1), but that '
          'is a different statistic measured in different cells. |')

    print()
    print('## Sources, cell by cell')
    print()
    print('| row | cell | artefact |')
    print('|---|---|---|')
    rows = [
        ('1', 'apparent finding', '`results/E2-PLAN.md` at `c823393`, the attribution statistic fixed before the runs; midpoints from E1'),
        ('1', 'registered challenge', '`results/E2-PLAN.md` at `c823393`'),
        ('1', 'pre-calibration outcome', '`results/E2-REPORT.md`'),
        ('1', 'post-calibration', '`results/W8-effect-size-accounting.json`, `matched` and `matchedA4`, from `results/E2E-analysis.json`'),
        ('2', 'apparent finding', '`results/E2-PLAN.md` at `c823393`, the 2x2 showing E1\'s two caps'),
        ('2', 'registered challenge', '`results/E2-PLAN.md` at `c823393`'),
        ('2', 'pre-calibration outcome', '`results/E2-REPORT.md`'),
        ('2', 'post-calibration', '**none — see the gaps below**'),
        ('3', 'apparent finding', '`results/E2B-PLAN.md` at `a741d68`'),
        ('3', 'registered challenge', '`results/E2B-PLAN.md` at `a741d68`'),
        ('3', 'pre-calibration outcome', '`results/E2B-REPORT.md`'),
        ('3', 'post-calibration', '**none — see the gaps below**'),
    ]
    for r in rows:
        print('| %s | %s | %s |' % r)

    print()
    print('## A6 is a different correction')
    print()
    print('All three rows appear in A6\'s conclusions table as surviving the '
          '**estimator** correction, which is not the calibration correction. '
          'A6\'s registered rows, at `c3aee75`:')
    print()
    for k in ('a6_conc', 'a6_cap', 'a6_h'):
        print('> %s' % QUOTES[k][2])
    print()
    print('A6 recomputed utilisation at SAFE points only. The calibration '
          'correction is a different operation: it reduced the configured sleep '
          'by the measured per-request overhead and re-ran the two boundaries.')

    print()
    print('## Gaps, named rather than filled')
    print()
    print('**Rows 2 and 3 have no post-calibration artefact.** The corrected '
          'corpus is two cells: c10 at `S = 5 ms`, concurrency 10, queue cap 500, '
          'and c50 at `S = 25 ms`, concurrency 50, queue cap 2500, both at '
          '`C = 2000`. Across its 33 boundary runs there is no cell with swapped '
          'caps and none at `C = 400`. So neither `f` nor `h` has a '
          'post-calibration value, and the last column of those two rows states '
          'that rather than reasoning to one.')
    print()
    print('**Row 2\'s apparent finding was never affirmed by the campaign.** The '
          'cap hypothesis was refuted by its own registered test, before '
          'calibration. The finding that survived E2 is its negation: the '
          'admission limit does not govern the boundary. Row 1 and row 3 are '
          'findings the campaign affirmed and the calibration correction '
          'dissolved; row 2 is a hypothesis the campaign eliminated on its own. '
          'They do not have the same standing, and §8 should not present them as '
          'though they do.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
