#!/usr/bin/env python3
"""T2: per-cell resolution, under the maximum numerator section 4 names.

Emits TWO tables from one set of rows: the article's compact four-column
table (tab:resolution) and Supplement S1's full eleven-column one
(tab:resolution-full, marked :s1). Draft 4 ruling.

Every value is read from committed artefacts; nothing is typed in.

  boundary files        rhoAchieved per repetition, runs, the rate bracket
  E2D calibration       C_measured (the median across a cell's saturation runs
                        of each run's maximum 30 s sustained served rate)
  W7 denominator        C_measured's own range -- the plateau min and max ONLY

W7 also carries rhoEffAtCmin / rhoEffAtCmedian / rhoEffAtCmax. Those use a4Rate,
a MEDIAN numerator, and are the wrong statistic for this table. They are not
read here.

Usage: python3 scripts/make_table2.py > figures/T2-resolution.md
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from precision import u, is_coarse          # noqa: E402

STEP_RPS = 5
CAL = json.load(open('results/E2D-capacity-calibration.json'))['cells']
W7 = json.load(open('results/W7-denominator-uncertainty.json'))['cells']
CELLS = [
    ('E1 c10/C0', 'results/boundaries/c10-C0.json'),
    ('E1 c10/C1', 'results/boundaries/c10-C1.json'),
    ('E1 c50/C0', 'results/boundaries/c50-C0.json'),
    ('E1 c50/C1', 'results/boundaries/c50-C1.json'),
    ('E2 c10@Q2500', 'results/e2/c10-Q2500/boundaries/c10-C0.json'),
    ('E2 c50@Q500', 'results/e2/c50-Q500/boundaries/c50-C0.json'),
    ('E2b C=400', 'results/e2b/boundaries/c50-C0.json'),
]


def row(label, path):
    b = json.load(open(path))
    bd = b['boundary']
    lo, hi = bd['lastSafeRl'], bd['firstNonSafeRl']
    pt = next(p for p in b['points'] if p['rl'] == lo)
    rhos = pt['rhoAchieved']
    c_config = pt['runs'][0]['faultCapacity']
    c_meas = CAL[label]['trueCapacity']          # field name: see METHOD-AUDIT item 33
    w7 = W7[label]
    # W7's median must be the same C_measured, or the range belongs to something else
    assert abs(w7['median'] - c_meas) < 0.06, label
    return {
        'cell': label,
        'C_config': c_config,
        'C_measured': c_meas,
        'step': STEP_RPS,
        'stepFrac': STEP_RPS / c_meas,
        'bracket': (lo, hi),
        'width': hi - lo,
        'n': len(rhos),
        'spreadRps': (max(rhos) - min(rhos)) * c_config,
        'rhoEff': max(rhos) * c_config / c_meas,    # MAXIMUM numerator
        'cmRange': (w7['min'], w7['max'], w7['n']),
    }


def main():
    rows = [row(*c) for c in CELLS]
    print('# T2 — per-cell resolution of the boundary estimate')
    print()
    print('Generated by `scripts/make_table2.py` from committed artefacts. The '
          'numerator of ρ_eff,safe is the **maximum** achieved rate across the last '
          'SAFE point\'s repetitions, the per-cell value §IV defines.')
    print()
    # The build sets ONLY the pipe table that follows each marker. Everything
    # else in the generated file -- heading, provenance paragraph, column notes
    # -- is artefact documentation and must not reach either document.
    #
    # TWO TABLES FROM ONE SET OF ROWS, per the Draft 4 ruling. The article gets
    # the three quantities its argument uses; Supplement S1 gets every column,
    # marked :s1. Both are generated from the same `rows`, so the compact table
    # cannot drift from the full one.
    print('<!-- table:tab:resolution -->')
    print('| Cell | Boundary bracket (rps) | Resolution Δρ | ρ_eff,safe |')
    print('|---|---|---:|---:|')
    for r in rows:
        lo, hi = r['bracket']
        print('| %s | [%d, %d] | %.4f | %s |'
              % (r['cell'], lo, hi, r['stepFrac'],
                 u(r['rhoEff'], is_coarse(r['cell']))))
    print()
    print('**Resolution Δρ is the NORMALISED per-cell resolution**, the bisection '
          'step divided by that cell\'s C_measured -- not the raw bracket width in '
          'requests per second. The coarsest cell is E2b at C = 400, where Δρ = '
          '0.0127; the finest are the C = 2000 cells at 0.0025. A margin smaller '
          'than a cell\'s Δρ is not resolvable in that cell, which is the whole '
          'use of the column, and a raw width of 5 rps means different things at '
          'C = 400 and at C = 2000.')
    print()
    print('<!-- table:tab:resolution-full:s1 -->')
    print('| cell | C_config | C_measured | step (rps) | step / C_measured '
          '| rate bracket (rps) | width (rps) | n | replicate spread (rps) '
          '| ρ_eff,safe | C_measured range (rps) |')
    print('|---|---:|---:|---:|---:|---|---:|---:|---:|---:|---|')
    for r in rows:
        lo, hi = r['bracket']
        mn, mx, k = r['cmRange']
        print('| %s | %d | %.1f | %d | %.4f | [%d, %d] | %d | %d | %.1f | %s | %.1f – %.1f (n = %d) |'
              % (r['cell'], r['C_config'], r['C_measured'], r['step'], r['stepFrac'],
                 lo, hi, r['width'], r['n'], r['spreadRps'],
                 u(r['rhoEff'], is_coarse(r['cell'])), mn, mx, k))
    print()
    print('**Columns.** *C_measured* is the median across a cell\'s saturation runs '
          'of each run\'s maximum 30-second sustained served rate. *Rate bracket* is '
          'the bisection bracket in probed recovery rate, [last SAFE, first '
          'non-SAFE], and *width* its difference. *n* and *replicate spread* are for '
          'the last SAFE point: the number of repetitions, and the range of their '
          'achieved total rate. *ρ_eff,safe* is that point\'s maximum achieved rate '
          'over C_measured, given at the cell\'s own precision — three decimals, two '
          'for E2b at C = 400, never four. *C_measured range* is the lowest and '
          'highest per-run plateau behind the median, with their count.')
    print()
    print('*Step / C_measured* is the search resolution itself, so it is given to '
          'four decimals: at three, six of the seven cells would read 0.003 or '
          '0.004 and the column would stop distinguishing them.')
    print()
    print('Two cells read 1.000 at this precision while exceeding 1.0 unrounded, '
          'which §IV explains: C_measured is an estimate, not a ceiling.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
